### PR TITLE
Added Magnet Closed Delay configuration option

### PR DESCRIPTION
**Pull request by XxTopKillerzZ**
Based on #118 I figured I could implement the ability to have different timers for the triggered delay for Motion and PIR sensors.
I hope this works for everyone. It is possible to maintain the old logic, is just applying the same delay in both config options.
Works the same way as Motion Off Delay but for magnet sensors
Sensors other than Magnet still use the old timer value.

### CODE REVIEW

**Comment by XxTopKillerzZ** [comment]
I made the pull request to the wrong destination branch. Updated to dev

**Comment by XxTopKillerzZ** [comment]
I have changed my code to support what we talked in #118
I also done an array to map each sensor type to the delay wanted in case we want to adapt in the future. In case a new type of sensor is added and forgotten to be put in the delay map it should throw an error.

- Translations still need to be done. I don't think I nailed the description :(
- I assume a delay of 0s for sensors of type AlSensorType.UNKNOWN and AlSensorType.IGNORED
- The variables in the code follow more less this scheme:
    1. MotionOffDelay
    2. MagnetClosedDelay
    3. EmergencyOffDelay

    They could possible all be related to Off since it's really a trigger delay.
    Magnet also relates to Wired sensors and Motion also relates to Camera sensors and the variables dont tell it

Tell me whats your liking so I can change what you want.

I have one known bug yet to search for a fix. When I configure the integration for a panel and change the delays, they do not change. It prints the following messages in the console:

DEBUG (MainThread) [custom_components.visonic.pyvisonic] [Settings] Motion Off Delay set to 120
DEBUG (MainThread) [custom_components.visonic.pyvisonic] [Settings] Magnet closed Delay set to 5
DEBUG (MainThread) [custom_components.visonic.pyvisonic] [Settings] Emergency Off Delay set to 120

It keeps using the default values and its configurable, to reproduce you just need to click configure in the UI and change the delays. Might be some typo in some variable. I will find it when I come home again

**Comment by XxTopKillerzZ** [comment]
Found and fixed the bug. Integration was using new value but the value printed in the console was the default one.

**Comment by davesmeghead** [comment]
OK so I've gone for it in a big way!

I've merged in your push with my local changes and pushed a new Dev Release
I've also been updating the Wiki, I've included your changes and pushed a new Wiki Page

If you get the chance to check it then please do so and give comments

I plan to spread the word in the main forum page that there's a Dev release with breaking changes and a new Wiki Page (after I do a bit more testing).

Dave

**Comment by XxTopKillerzZ** [comment]
Thank you. I will pull your changes and continue to test dev release. 
Did you had a chance to test the different delays? 
The wiki entries for the delay settings are good. I will read the rest when I’m home. Are you planning to do some type or release notes with the new features/changes when merged with master?

**Pull request merged**
